/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as DocsPackageIndexRouteImport } from './routes/docs/$package/index'
import { Route as DocsPackageSplatRouteImport } from './routes/docs/$package/$'

const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPackageIndexRoute = DocsPackageIndexRouteImport.update({
  id: '/docs/$package/',
  path: '/docs/$package/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPackageSplatRoute = DocsPackageSplatRouteImport.update({
  id: '/docs/$package/$',
  path: '/docs/$package/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/$package/$': typeof DocsPackageSplatRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/$package/$': typeof DocsPackageSplatRoute
  '/docs/$package': typeof DocsPackageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/$package/$': typeof DocsPackageSplatRoute
  '/docs/$package/': typeof DocsPackageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/' | '/docs/$package/$' | '/docs/$package/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/docs/$package/$' | '/docs/$package'
  id:
    | '__root__'
    | '/(home)/'
    | '/docs/'
    | '/docs/$package/$'
    | '/docs/$package/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsPackageSplatRoute: typeof DocsPackageSplatRoute
  DocsPackageIndexRoute: typeof DocsPackageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$package/': {
      id: '/docs/$package/'
      path: '/docs/$package'
      fullPath: '/docs/$package/'
      preLoaderRoute: typeof DocsPackageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$package/$': {
      id: '/docs/$package/$'
      path: '/docs/$package/$'
      fullPath: '/docs/$package/$'
      preLoaderRoute: typeof DocsPackageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsPackageSplatRoute: DocsPackageSplatRoute,
  DocsPackageIndexRoute: DocsPackageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
